apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app
  namespace: pingpong-dev
  labels:
    app: pingpong-tracker
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pingpong-tracker
  template:
    metadata:
      labels:
        app: pingpong-tracker
    spec:
      containers:
      - name: pingpong-app
        image: pipelinedave/ping-pong-tracker:dev-aac6975405c9ef6ffc7d3d36ffa43d956f33eddf
        ports:
        - containerPort: 4173
        env:
        - name: NODE_ENV
          value: "development"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
