apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pingpong-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:DawgSons/ping-pong-tracker.git'
    targetRevision: HEAD
    path: kubernetes/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pingpong-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
